<?php

use Drupal\movie_controller\Form\MovieForm;

/**
 * Implementing hook_theme().
 */

function movie_controller_theme($existing, $type, $theme, $path) {
  
  $templates = [
    'movie'=> array(
      'variables'=> array('datas'=>array(),'finds'=>array(),'types'=>array(),'form' => NULL,),
      'render element' => 'form',
         'template' =>'movie',
         'pager' => [
          'type' => 'pager',
        
          
        ],
    )
    ];
    return $templates;
}
